# Generated by Django 4.0.2 on 2022-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_counselor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_counselor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counselor',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_normal',
            name='is_counselor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_normal',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
